const actionType = {
  CHANGE_HOME_STATEVALUE: "CHANGE_HOME_STATEVALUE",
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
  GETUSERINFO: "GETUSERINFO",
  SETCHECKCENTERDATA: "SETCHECKCENTERDATA",
  SETLOANFRAMDATA: "SETLOANFRAMDATA",
  UPDATECHECKCENTERDATA:"UPDATECHECKCENTERDATA",
  UPDATEDUEDILIGENCEDETDETAIL: 'UPDATEDUEDILIGENCEDETDETAIL',
  UPDATEDUEDILIGENCEDETDATA: 'UPDATEDUEDILIGENCEDETDATA',
};

export { actionType };
